version: '3'
services:
  spacy:
    image: ai-adventure-spacy
    volumes:
      - ./src:/var/task/src
      - ./lambda_function.py:/var/task/lambda_function.py
    ports:
      - $SPACY_SERVER_PORT:8080
    environment:
      - TRANSFORMERS_CACHE=/root/.cache/huggingface/hub
      - SPACY_SERVER_ENV=dev