version: '3'
services:
  spacy:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/var/task/src
      - ./lambda_function.py:/var/task/lambda_function.py
    ports:
      - $SPACY_SERVER_PORT:8080