version: '3'
services:
  spacy:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/home/app/src
    ports:
      - $SPACY_SERVER_PORT:80
    environment:
      - SPACY_SERVER_HOST=0.0.0.0
      - SPACY_SERVER_PORT=80