name: Wait for Lambda status

inputs:
  lambda-status:
    required: true
    type: string

runs:
  using: "composite"
  steps:        
    - shell: bash
      run: |
        while ! (aws lambda wait ${{ inputs.lambda-status }} --function-name ${{ env.FUNCTION_NAME }}); do
          :
        done
    