name: Deploy to Amazon ECS

on:
  push:
    branches: [ "aws-lambda-runtime" ]

env:
  AWS_REGION:     us-east-1 
  ECR_REPOSITORY: ai-adventure-spacy
  ECR_CACHE_TAG:  ai-adventure-spacy-cache
  FUNCTION_NAME:  ai-adventure-spacy

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker buildx build \
            --push \
            --platform linux/amd64 \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --cache-from type=registry,ref=$ECR_REGISTRY/$ECR_REPOSITORY:$ECR_CACHE_TAG \
            --cache-to mode=max,image-manifest=true,type=registry,ref=$ECR_REGISTRY/$ECR_REPOSITORY:$ECR_CACHE_TAG \
            -f docker/Dockerfile .

        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
    # - name: AWS Lambda Deploy
    #   uses: appleboy/lambda-action@v0.1.9
    #   with:
    #     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws_region: ${{ env.AWS_REGION }}
    #     function_name: ${{ env.FUNCTION_NAME }}
    #     image_uri: ${{ steps.build-image.outputs.image }}
    #     environment: SPACY_SERVER_ENV=prod